TokTok/toxic

.travis.yml, Makefile, src/api.c, src/python_api.c
Based on `-DPYTHON`, instead of based on which files are listed in the
source list. This simplifies people's lives when compiling from the
command line with `cc *.c`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/1)
=> Conditionally compile api.c and python_api.c contents.

src/audio_call.c, src/global_commands.c, src/prompt.c, src/prompt.h, src/toxic.c, src/toxic.h, src/video_call.c, src/windows.c
So it's easy to map from implementation to the event without looking at
the `tox_callback_*` calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/7)
=> Rename callback implementations to be of the form `on_$event`.

BUILD.bazel
Import libs currently also point to the global system installed versions,
but at least we have the freedom to import them properly later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/10)
=> Use bazel import libs instead of global `-l` flags.

BUILD.bazel
These should be fixed, but for now we leave it as warning, not error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/17)
=> Ignore warning about unused result.

src/xtra.c, src/xtra.h
Privatise some functions that don't need to be public
Fix struct names starting with _ char
Remove unnecessary memset of Xtra struct in init_xtra()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/25)
=> Cleanup xtra.c

src/prompt.c, src/prompt.h, src/toxic.c
This change prevents toxic from forcing the default status message when it's otherwise empty, with the exception of new profiles. In other words, users can now set a blank status message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/30)
=> Allow empty status messages

src/api.c, src/api.h, src/autocomplete.c, src/autocomplete.h, src/chat.c, src/chat_commands.c, src/execute.c, src/global_commands.c, src/group_commands.c, src/groupchat.c, src/misc_tools.c, src/misc_tools.h, src/prompt.c, src/term_mplex.c, src/toxic.c
In addition, I removed the ability for the `status` command to double as the `note` command because it's an unnecessary special case that causes complications.
(Note: The file_type() function was added for future use)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/31)
=> Remove requirement for argument strings and paths to be enclosed in quotes for all commands

src/audio_call.c, src/chat.c, src/chat.h, src/friendlist.c, src/friendlist.h, src/groupchat.c, src/groupchat.h, src/prompt.c, src/prompt.h, src/toxic.c, src/windows.c, src/windows.h
- Fix a couple memory leaks
- Properly clean up `friendlist` window on exit
- Refactor `ToxWindows` so that they're now handled via pointers rather than structs. This significantly reduces the amount of heap memory allocated to the global windows array for an average use case.
- Use `uint8_t` to index windows array, and use C99 style loop counter declarations for related indexing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/32)
=> ToxWindow refactor

src/friendlist.c
This call to `init_friend_AV()` is necessary because `del_friend_AV()` is called when a contact is blocked but not deleted. This probably fixes a segfault I ran into after unblocking and then deleting a contact.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/33)
=> Re-init AV for unblocked contacts (possible segfault fix)

doc/toxic.conf.5, doc/toxic.conf.5.asc, misc/toxic.conf.example, src/settings.c, src/settings.h, src/toxic.c
Re-created PR per maintainer's request.
This change enhances the default setting of 3000 milliseconds for the notification timeout by making the value a user config option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/38)
=> Add config option for the notification timeout duration

cfg/checks/video.mk
This prevents toxic from failing to compile with default build options when the video dependencies are present but openal isn't.
The other way to solve this would be to fix the code so that video can compile without audio, but I think it's reasonable to make audio a dependency for video. I am open to input on that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/40)
=> Check for openal lib before attempting to build with video support

src/groupchat.c, src/groupchat.h
`num_peers` being unsigned was causing a bug that broke groupchat peerlist scrolling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/41)
=> Fix integer types for correct behaviour

src/chat_commands.c, src/global_commands.c, src/group_commands.c, src/groupchat.c, src/groupchat.h, src/misc_tools.c, src/toxic.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/43)
=> Load conference titles on startup for saved conferences

src/audio_call.c
The call answerer's call state is no longer set by toxcore after calling `toxav_answer()`. Therefore when the answerer would terminate the call, it would see its own call state as non-existent and never inform the caller of the termination, leaving them in a broken call. I'm not sure if this is a toxic or toxcore bug, or an API "improvement", as the AV API makes no mention of when or if the call state should be set. This PR fixes the problem for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/44)
=> Fix A/V hangup bug

Makefile, src/avatars.c, src/groupchat.c, src/line_info.c, src/misc_tools.c, src/misc_tools.h, src/name_lookup.c
Self explanatory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/49)
=> Some misc fixes

src/toxic.c
UPPER_CASE enum types are deprecated and will be removed in 0.3.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/50)
=> Migrate to Camel_Case enum types.

.github/FUNDING.yml
YAML apparently likes to have this marker, so let's have it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/52)
=> Fix yamllint warning about missing document start marker.

BUILD.bazel, Makefile, src/audio_call.c, src/autocomplete.c, src/bootstrap.c, src/chat.c, src/chat_commands.c, src/execute.c, src/file_transfers.c, src/file_transfers.h, src/friendlist.c, src/global_commands.c, src/group_commands.c, src/groupchat.c, src/groupchat.h, src/input.c, src/input.h, src/misc_tools.c, src/misc_tools.h, src/name_lookup.c, src/prompt.c, src/toxic.c, src/video_call.c, src/video_device.c, src/windows.c, src/xtra.c
Addressing issue https://github.com/TokTok/toxic/issues/53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/55)
=> Fix unused parameter warnings and add -Wunused-parameter to makefile

src/audio_call.c, src/audio_device.c, src/autocomplete.c, src/chat_commands.c, src/configdir.c, src/execute.c, src/file_transfers.h, src/global_commands.c, src/line_info.c, src/misc_tools.c, src/misc_tools.h, src/name_lookup.c, src/settings.c, src/settings.h, src/term_mplex.c, src/toxic.c, src/video_call.c, src/video_device.c, src/xtra.c
These are needed to compile on some strict Linuxes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/64)
=> Add feature flags and missing #includes.

BUILD.bazel, src/audio_call.c, src/audio_device.c, src/autocomplete.c, src/chat_commands.c, src/configdir.c, src/execute.c, src/file_transfers.h, src/global_commands.c, src/line_info.c, src/misc_tools.c, src/misc_tools.h, src/name_lookup.c, src/settings.c, src/settings.h, src/term_mplex.c, src/toxic.c, src/video_call.c, src/video_device.c, src/xtra.c
This reverts commit dd5fa236ae1dbd7451420420b0f40f05708bc3c2.
Also, set `-std=gnu99` in Bazel build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/65)
=> Revert "Add feature flags and missing #includes."

src/toxic.c
This fixes a use after free bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/67)
=> Terminate notify before windows

.travis.yml, src/video_device.c
lock/unlock are always expanded in a context followed by a semicolon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/66)
=> Remove extra semicolon in lock/unlock macros.

doc/toxic.1, doc/toxic.1.asc, src/toxic.c, src/windows.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/74)
=> Add option for toxcore logging in stderr

src/toxic.c, src/windows.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/87)
=> feat: add option to disable LAN

src/xtra.c
The problem with the bell notifications only happens when Toxic is
compiled with X11 support, but does not run under X. This commit changes
toxic's behavior such that it behaves identically when not running under an
X session, no matter if it has been compiled with X11 support or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/88)
=> fix: Fix non-working bell notifications

Makefile
The full error:
```
Incorrect file specified: '>'. 
Command 'cc -MM -g -std=gnu99 -pthread -Wall -Wpedantic -Wunused -fstack-protector-all '-DTOXICVER="0.8.4_r1903"' -DHAVE_WIDECHAR -D_XOPEN_SOURCE_EXTENDED -D_FILE_OFFSET_BITS=64 '-DPACKAGE_DATADIR="/usr/local/share/toxic"' -DX11 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/opus -I/usr/include/x86_64-linux-gnu /mnt/z/toktok/toxic/src/avatars.c > /mnt/z/toktok/toxic/build/avatars.d'
```
Not sure exactly what's going on since clion pushes commands to WSL via ssh and things, but this fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/92)
=> fix: Incorrect file specified error when building in WSL from CLion

src/audio_call.c, src/audio_call.h, src/audio_device.c
Continuation of https://github.com/TokTok/toxic/pull/96
This also fixes a long-standing use after free bug. I'm not entirely sure why this PR triggered it, which worries me.
Edit: The call was being cancelled twice, which caused a cascading failure that prevented data structures from being properly cleaned up. All fixed now. This bug was caused by a previous fix for another bug in https://github.com/TokTok/toxic/pull/44. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/98)
=> cleanup: Dynamically allocate audio frame buffer memory

Makefile
No gnu99 extensions are used or will be used
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/103)
=> chore: Use c99 standard instead of gnu99

Makefile, src/audio_device.c, src/autocomplete.c, src/autocomplete.h, src/avatars.c, src/bootstrap.c, src/chat.c, src/file_transfers.c, src/friendlist.c, src/global_commands.c, src/groupchat.c, src/groupchat.h, src/misc_tools.c, src/misc_tools.h, src/prompt.c, src/qr_code.c, src/toxic.c
VLA's are inherently unsafe so the safest option is to not use them. The trade off here is a lot of extra code for mallocs/frees and more possible memory leaks. But I think that's a small price to pay for greatly reducing the possibility of stack corruption.
I also added the -Wvla compile option to the Makefile, which gives a warning when VLA's are used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/100)
=> cleanup: Convert all variable length arrays to heap allocations

src/avatars.c, src/chat.c, src/chat_commands.c, src/friendlist.c, src/line_info.c, src/misc_tools.c, src/term_mplex.c, src/toxic.c
- realloc needs to be error checked
- use correct format specifiers
- make sure `optarg` and `DATA_FILE` aren't null before using them
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/106)
=> cleanup: Fix a few issues

src/chat_commands.c, src/friendlist.c, src/line_info.c, src/term_mplex.c, src/toxic.c
The legacy profile code was added over 5 years ago and no longer serves a purpose.
edit: added a few more null checks for `optargs`, some missing `malloc` null checks, and fixed a comparison between a `widechar` and `char`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/107)
=> cleanup: Remove legacy code and more code cleanup

src/chat.c
If the new path is too long for the buffer we cancel the file transfer and return an error instead of truncating the file name and continuing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/110)
=> cleanup: fix bad behaviour with duplicate file names

src/audio_device.c, src/misc_tools.c, src/misc_tools.h, src/notify.c, src/toxic.c, src/video_device.c, src/xtra.c
usleep was declared obsolete in POSIX.1-2001
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/109)
=> cleanup: Replace deprecated usleep function with nanosleep

src/chat.c
Addressing https://github.com/TokTok/toxic/issues/111
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/112)
=> cleanup: Filter invalid file names for inbound file transfers

Makefile, src/chat.c, src/chat_commands.c, src/chat_commands.h, src/conference.c, src/conference.h, src/conference_commands.c, src/conference_commands.h, src/execute.c, src/execute.h, src/friendlist.c, src/friendlist.h, src/global_commands.c, src/global_commands.h, src/help.c, src/help.h, src/input.c, src/line_info.c, src/log.c, src/log.h, src/misc_tools.c, src/misc_tools.h, src/prompt.c, src/python_api.c, src/toxic.c, src/toxic.h, src/windows.c, src/windows.h
This is in line with the toxcore API naming scheme and is in preparation for the merge with the new groupchat implementation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/113)
=> chore: Rename: groupchats -> conferences

src/chat.c, src/conference.c, src/notify.c, src/notify.h
A ToxWindow's notifications need to be halted before the window is freed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/119)
=> fix: Race condition

Makefile, src/audio_call.c, src/avatars.c, src/chat.c, src/conference.c, src/file_transfers.c, src/friendlist.c, src/global_commands.c, src/help.c, src/log.c, src/name_lookup.c, src/notify.c, src/prompt.c, src/toxic.c, src/video_device.c
This is cleaner and much less prone to bugs.
`Wno-missing-bracers` was added to the makefile because Clang was giving lots of false positives. `Wmissing-field-initializers` was added because it basically does what `Wmissing-bracers` does but without the false positives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/122)
=> cleanup: Use compound literals to zero out structs instead of memset

src/message_queue.c, src/message_queue.h, src/toxic.c
We now attempt to send all queued messages per call to cqueue_try_send() instead of just the oldest message in the queue. This speeds things up substantially.
Also fixed a very unlikely bug where the read receipt might wrap around to zero which we used as a reserved value for an unsent message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/123)
=> cleanup: Refactor message queue

src/message_queue.c
- It's no longer possible for messages to be sent out of order
- Check if logger is enabled before doing pointless API calls
- Fix linked list bug (a part of the code that almost never executes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/124)
=> fix: bugs/issues with the message queue

src/avatars.c, src/avatars.h, src/chat.c, src/chat_commands.c, src/file_transfers.c, src/file_transfers.h, src/windows.c
- Fix bug causing failed avatar transfers to be sent as normal file transfers when a friend goes offline and comes back online
- Remove some unused members of the FileTransfer struct
- Rename filenum -> filenumber and friendnum -> friendnumber
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/126)
=> fix: some issues with file transfers

src/audio_device.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/133)
=> fix: playing unallocated memory on opening audio device

src/chat.c, src/conference.c, src/conference.h, src/conference_commands.c, src/friendlist.c, src/global_commands.c, src/log.c, src/log.h, src/prompt.c
The conference logging implementation was written a long time ago when groupchats didn't have a unique identifier provided by the toxcore API, so there was no easy way to keep track of unique log names across restarts or title changes.
- Conference logging now behaves the same as 1-on-1 chats: Instead of creating a new log file every time we restat the client we use the unique conference ID to keep track of path names. This also allows us to load history for saved groups on client startup
- Added a log init function / general code refactor.
- Fixed a bug that caused log files to be created even when logging is disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/134)
=> feat: Refactor/improve logging

doc/toxic.conf.5, doc/toxic.conf.5.asc, misc/toxic.conf.example, src/audio_call.c, src/conference.c, src/settings.c, src/settings.h
This allows us to configure chat/conference channels independently. The default settings prioritize quality for 1-on-1 chats, and bandwidth for conferences.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/136)
=> feat: Add config settings for audio channels

src/friendlist.c, src/misc_tools.c, src/prompt.c, src/toxic.c, src/windows.c, src/windows.h
- Bottom tab now only shows indices of active chat windows unless focused (this mostly remedies the issue of tabs disappearing off the right of the screen when you have numerous chats open)
- Always focus Home screen on startup instead of the last loaded conference
- Conference tab names are no longer prefixed with the conference number
- Home and Contact tab names are now capitalized
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/141)
=> feat: Some UI improvements

src/api.c, src/audio_call.c, src/chat.c, src/conference.c, src/friendlist.c, src/global_commands.c, src/log.c, src/python_api.c, src/xtra.c
- Create backup of duplicate log file instead of deleting it (this case should never occur, but just in case it does it's good to handle it without any data loss)
- Fix race condition in `draw_peer()`
- Handle `realloc_peer_list()` error
- Remove dead code in `cmd_conference()`
- Reduce scope of a few variables
- Fix possible buffer truncation in api.c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/139)
=> cleanup: Some code cleanup and fixes

src/misc_tools.c
The conference number needs to be displayed in the tab name so that you can invite friends to conferences
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/146)
=> fix: UI regression 

src/global_commands.c, src/notify.c, src/windows.c, src/windows.h
A counter now increments in the bottom bar for unfocused windows showing how many unread messages are pending. Tabs with no pending messages show `[*]` instead of their index (showing the index is useless and somewhat confusing, as they can go out of order and can be mixed up with conference numbers)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/150)
=> feat: Add notification counters to bottom tab

src/line_info.c, src/line_info.h, src/settings.h
<s>There might be a more efficient way of doing this, but I haven't noticed any interface lag issues with my limited testing.</s>
Edit: I ended up doing it the more efficient way because there's really no excuse not to.
Two things to note: 
1. This reverts this commit https://github.com/TokTok/toxic/commit/d6fdac973902457c7a94ec3113253838cfa12c53 which I don't really know why I approved of in the first place
2. It doesn't attempt to handle multi-byte characters. That's a pretty big undertaking which I'll leave for another day.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/149)
=> feat: Implement word wrapping

src/chat.c, src/conference.c, src/prompt.c
When a string fails to convert from widechar to multibyte we print an error message and clear the buffer instead of trying to send or execute an empty line (which leads to cascading bugs).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/153)
=> fix: Properly handle failures to convert widechar strings to multibyte

src/line_info.c, src/line_info.h, src/message_queue.c
Instead of trying (and failing) to correctly calculate the number of lines on the screen a given message will need space for, we dynamically set the value both on initiation of a new line, and whenever that line is printed to the screen using the `print_wrap()` function.
This should fix the screen occasionally not scrolling down the correct number of lines when a new message is printed.
Edit: Also fixed an issue with the line format breaking if a line contained newlines or no spaces
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/151)
=> fix: some off by one bugs with line scrolling and some cleanup

INSTALL.md, Makefile, cfg/targets/help.mk
The release now uses `-O2` and `flto`, and has no debug symbols. `-Wmissing-field-initializer` was removed due to false positives on newer versions of clang.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/143)
=> chore: Add release and LLVM asan build options

src/log.c
When renaming a log file, if the new name already exists we just start appending to it and delete the old file. There's no need to create a backup.
This fixes an issue where leaving and rejoining the same group multiple times will eventually lead to the logger not working due to trying to use the same file name over and over again. (when you join a new group the initial file name is set to a default name until you connect to the group).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/154)
=> fix: Another logging fix

src/autocomplete.c, src/file_transfers.c, src/line_info.c, src/line_info.h, src/message_queue.c
A line's line count now increments without messing up the formatting in cases where the noread flag wraps to the next line. 
Additionally, the way noread flags are handled has been refactored and made more efficient.
Edit: Also fixed a bug causing file transfer status bars to be truncated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/156)
=> fix: some display bugs

src/autocomplete.c
If a directory contains a single entry tab complete will no longer fail
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/157)
=> fix: tab complete bug

src/line_info.c, src/log.c
Print a warning if remove() fails, and check if the win pointer is null before using it (this is unnecessary but it's correct and shuts coverity up)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/159)
=> fix: a couple minor issues

src/api.c, src/audio_call.c, src/audio_device.c, src/autocomplete.c, src/chat.c, src/chat_commands.c, src/conference.c, src/conference_commands.c, src/execute.c, src/file_transfers.c, src/friendlist.c, src/global_commands.c, src/line_info.c, src/line_info.h, src/log.c, src/misc_tools.c, src/misc_tools.h, src/name_lookup.c, src/prompt.c, src/toxic.c, src/video_call.c, src/video_device.c
Instead of making the caller of `line_info_add` provide a timestamp string we just have them set a boolean value and let the callee create the string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/163)
=> cleanup: Remove lots of duplicate code related to printing timestamps

src/conference.c
This appears to be a toxcore bug, but nonetheless it looks ugly. Also changed `group` -> `conference` for join/part messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/164)
=> fix: Don't announce when ghost peers leave the group

Makefile
When a user provides variable=value as an argument to make, all
assignments to that variable are ignored within the Makefile because the
user has explicitly overrode variable to be "value". This made the
ENABLE_ASAN assignment to be ignored, resulting in Toxic always enabling
ASAN unless you run `make ENABLE_ASAN=disabled`, which is not
documented and not how it's intended to work. This can be fixed by
prefixing the assignment with "override", but to be in line with other
argument assignments we just change the variable name.
See more at:
https://www.gnu.org/software/make/manual/html_node/Overriding.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/178)
=> fix: Makefile assignment bug

script/build-minimal-static-toxic.sh
The intention is that JFreegman would run it locally on his machine for
every Toxic release and publish the build artifacts on GitHub for
download, similarly to how the qTox team makes release builds. This
should mitigate the loss of the Jenkins build server to some extent,
which used to provide Toxic builds before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/176)
=> feat: add a script for building minimal static toxic

src/prompt.c
Fixes https://github.com/JFreegman/toxic/issues/557
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/180)
=> fix: bug preventing the /clear command from working in Home window

src/windows.c
This always bothered me but I was too lazy to fix it. This is also preemptively fixing buggy behaviour for when the game PR gets merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/182)
=> chore: Show previous window instead of Home after closing a window

src/prompt.c
This line doesn't appear to be doing anything useful - most likely a leftover from the recent UI overhaul
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/183)
=> fix: buggy behaviour when printing non-ascii characters in Home input field

src/audio_device.c, src/notify.c
Possible fix for https://github.com/TokTok/toxic/issues/184
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/185)
=> fix: Add two missing mutex unlocks before return

BUILD.bazel
This way we at least know it doesn't crash on load. Some code runs. We'll
want some real tests at some point, but this ensures *something* works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/194)
=> chore: Add a bazel test that calls toxic with `--help`.

src/api.c, src/audio_call.c, src/bootstrap.c, src/chat.c, src/conference.c, src/friendlist.c, src/friendlist.h, src/global_commands.c, src/name_lookup.c, src/prompt.h, src/settings.h, src/toxic.c, src/toxic.h, src/video_device.c, src/windows.c, src/windows.h
There is no check at all that the types of externs actually match the
type of the definition. This just accidentally was not a problem, but now
the compiler helps a bit in keeping it that way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/199)
=> cleanup: Reduce the amount of "extern" in .c files.

src/chat.c, src/chat_commands.c, src/file_transfers.c, src/file_transfers.h, src/friendlist.c, src/friendlist.h, src/windows.c
File transfers initiated for offline friends are now added to a queue and initiated all at once when the friend appears online.
I also did a little code cleanup in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/208)
=> feat: Implement file transfer queue for offline friends

src/chat.c, src/file_transfers.c, src/file_transfers.h
This fixes a bug where if you receive multiple file transfer requests simultaneously and they have the same path the files will overwrite each other.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/214)
=> fix: make sure we check for duplicate paths in pending file transfers list

src/chat.c, src/log.c, src/prompt.c, src/toxic.h
This will alert the user when the first three bytes of a new contact's public key is the same as any other contact in their list. These 3 bytes are used elsewhere in toxic for unique identification.
Also did a small refactor regarding the KEY_IDENT_BYTES define.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/215)
=> feat: add some simple impersonation detection on friend requests

src/line_info.c, src/line_info.h, src/toxic.h
This fixes a bug where printing a bunch of UTF8 chars with glyphs that have a size > 1 would make the entire chat window disappear. It also fixes an issue where said UTF8 chars would be truncated and generally not display correctly.
UTF8 printing is still not perfect, but this is a big improvement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/216)
=> fix: use widechars to display strings in the UI

src/line_info.c
The msg buffer was recently changed to wchar_t and I forgot about these comparisons.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/219)
=> cleanup: make sure we compare wchars to wchars instead of bytes

script/build-minimal-static-toxic.sh
Bump toxcore to v0.2.16 and add new msgpack dependency
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/221)
=> chore: update static musl build script

src/line_info.c, src/misc_tools.c
The wcswidth() function was silently failing when trying to convert
messages containing a newline to a widechar buffer which resulted
in the message showing up as an empty line. we now fall back
to using strlen to get the width of the string, which might still
cause minor display bugs when the message contains unicode, but is
still better than losing messages entirely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/222)
=> fix: bug causing messages containing newline byte to disappear

src/chat.c, src/game_base.c, src/message_queue.c, src/toxic.c
All-caps enum names have been deprecated for a while now and will go
away in 0.3.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/224)
=> cleanup: Remove all uses of deprecated enum names.

src/line_info.c
Patch by iphydf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/225)
=> fix: Use a small hack to get around an ncurses buffer overread

src/message_queue.c
This prevents us from accidentally using uninitialized memory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/toxic/227)
=> fix: Use calloc instead of malloc for new message queue items

BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/230)
=> chore: Use feature test macro instead of C standard.

script/build-minimal-static-toxic.sh, src/execute.c, src/groupchat_commands.c, src/groupchats.c, src/groupchats.h
Ignoring a peer now persists if they leave/disconnect and rejoin the group. In addition, ignore status is now displayed in the peer list sidebar as a red # symbol.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/231)
=> fix: group ignore functionality

src/chat_commands.c, src/game_base.c, src/game_base.h, src/game_chess.c, src/game_chess.h, src/global_commands.c
We previously used the length of the invite packet to determine if we were the host of a chess game. This allowed a friend to send an invite packet with a length of zero to trick you into starting a game of chess with yourself as the host. The effect of this was just a broken game in which neither peer could make a move. 
We now determine who the host is independently and in addition do more thorough packet size enforcement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/234)
=> fix: Properly determine the host of a chess game on initialization

doc/toxic.conf.5, doc/toxic.conf.5.asc, misc/toxic.conf.example, src/groupchats.c
Currently when your group connection messages are disabled in the config and someone manually leaves the group, you still see a part message. The purpose of this exception was to reduce spam due to poor connections without losing explicit part messages, but I think this can lead to confusion. Now the config option just blocks all group connection messages regardless of type.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/239)
=> fix: don't show group quit notifications when disabled in config

INSTALL.md, cfg/checks/check_features.mk, cfg/checks/tox_experimental.mk, script/build-minimal-static-toxic.sh, src/groupchat_commands.c, src/toxic.h
When you do a `/whois` on a group peer you now see their real IP address listed with the rest of their info. If they aren't accepting direct connections then you will see a placeholder value indicating as much. If you `/whois` yourself, you'll see either your own IP address or a placeholder value, depending on whether or not you're accepting direct connections.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/238)
=> feat: add IP address to group whois

src/conference.c, src/groupchats.c, src/line_info.c
Also do some safety null checks in group and conferences cleanup functions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/246)
=> fix: memory leak on groupchat window creation failure

src/line_info.c, src/misc_tools.c, src/misc_tools.h
The function expects a widechar count rather than a byte count.
This is a serious error that would lead to a buffer overflow
if not for the fact that the input char buffer passed to the
function uses the same size constant as the output wchar buffer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/251)
=> fix: incorrect buffer size passed to function

BUILD.bazel
The binary crashes (but works with `--help`), but at least it compiles.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/253)
=> chore: Preliminary support for arm64 cross compilation.

src/toxic.c
This message sounds like an error but it's not. The name lookup service hasn't been in use for years and isn't something users need to worry about.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/255)
=> cleanup: remove message about name lookup server list being empty from prompt

src/bootstrap.c
This race can occur if `do_tox_connection()` is called from the main thread while the nodes list loading thread is still running.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/244)
=> fix: possible data race

src/game_base.c
Doing this explicitly instead of relying on snprintf gets rid of a compiler warning
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/248)
=> cleanup: Manually truncate long game window names

src/conference.c, src/conference.h
We no longer report an error if we try to enable audio when audio is already enabled, or vice versa.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/256)
=> fix: error reporting for conference audio enabling and disabling

src/audio_call.c, src/audio_device.c, src/chat.c, src/conference.c, src/execute.c, src/friendlist.c, src/game_base.c, src/groupchats.c, src/notify.c, src/osx_video.m, src/video_call.c
This assert can give odd compile errors and is unnecessary. We can easily prove that sizeof(ret->name) is <= sizeof(buf) as sizeof(buf) includes sizeof(ret->name)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/259)
=> cleanup: Remove unnecessary assert and includes

src/chat.c, src/conference.c, src/execute.c, src/global_commands.c, src/global_commands.h, src/groupchats.c, src/help.c, src/prompt.c, src/toxic.c, src/windows.c, src/windows.h
In the future we hope to be able to make these permanently set via the toxic config file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/275)
=> feat: add a command that lets you change a tab name's colour

doc/toxic.conf.5, doc/toxic.conf.5.asc, misc/toxic.conf.example, src/chat.c, src/friendlist.c, src/friendlist.h, src/global_commands.c, src/misc_tools.c, src/misc_tools.h, src/settings.c, src/settings.h, src/toxic.c
Currently we only have one setting, but this can easily be expanded for a number of things such as auto-accepting file transfers, auto-logging, custom nicknames, message notifications etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/277)
=> feat: add support for friend config settings

Makefile, doc/toxic.conf.5, doc/toxic.conf.5.asc, misc/toxic.conf.example, src/chat.c, src/friendlist.c, src/friendlist.h, src/groupchats.c, src/groupchats.h, src/settings.c, src/settings.h, src/toxic.c
Currently we only have one setting, but this can be expanded for other settings such as notifications, auto-logging etc.
This commit also bumps the C standard to c11 from c99 so we can use static_assert().
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/278)
=> feat: add support for groupchat config settings

doc/toxic.conf.5, doc/toxic.conf.5.asc, misc/toxic.conf.example, src/chat.c, src/conference.c, src/execute.c, src/global_commands.c, src/global_commands.h, src/groupchats.c, src/help.c, src/misc_tools.c, src/misc_tools.h, src/prompt.c, src/settings.c, src/toxic.c, src/windows.h
- Add blue for tab name colours
- change all instances of purple to magenta to be consistent with
both ncurses and other parts of toxic
- Use color instead of colour for all user-facing variables
and messages in order to be consistent with previous spelling
conventions
- Sort colours the same way everywhere
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/281)
=> cleanup: fix some issues with customizable colours

src/conference.c, src/global_commands.c, src/groupchats.c, src/toxic.c, src/windows.h
The line colours now match the custom set colour scheme
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/282)
=> fix: group/conference peerlist border colors

src/friendlist.c, src/friendlist.h, src/toxic.c
The blocklist file is only ever created if the client blocks someone.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/287)
=> fix: don't report an error when blocklist file doesn't exist

INSTALL.md
Also removed the note about libnotify because it's already implied, as with all the other non-base libs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/297)
=> docs: add missing library to install instructions

src/video_call.c
It doesn't really make sense to default to a tiny 20x20 box
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/298)
=> fix: add default dimensions for video chat windows

src/autocomplete.c, src/chat.c, src/game_base.c, src/help.c, src/prompt.c
This was done in a half-assed way for statuses (only worked in the chat and home windows). Now it's done globally for all '/status', '/game', and '/color' command arguments
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/295)
=> feat: tab-complete will now work for command arguments

src/bootstrap.c, src/name_lookup.c
This makes it more clear to static analysers that the function actually exits after an error.
@robinlinden suggested marking the thread as `_Noreturn`, and while that worked in suppressing the false positive, it was also suppressing some ugly/confusing code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/291)
=> refactor: simplify error handling in name lookup thread

src/bootstrap.c, src/misc_tools.c, src/name_lookup.c, src/run_options.h, src/settings.c, src/settings.h, src/toxic.c, src/toxic.h
Instead of using the same default config file for every profile we now use the same name and path as the custom tox profile (with a .conf file extension), and create an empty config file if it doesn't already exist. In addition, if the user passes a non-existent file as a run option, we now create an empty file instead of returning an error.
Behaviour should not be changed for default profiles.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/300)
=> feat: config files are now tied to tox data files by default

src/settings.c
We don't use these in Toxic
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/303)
=> cleanup: remove an accidental VLA

doc/toxic.conf.5, doc/toxic.conf.5.asc, misc/toxic.conf.example, src/notify.c, src/settings.c, src/settings.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/315)
=> feat: add setting to hide the content of desktop notifications

Makefile, src/api.c, src/chat.c, src/chat_commands.c, src/conference.c, src/friendlist.c, src/game_snake.c, src/global_commands.c, src/line_info.h, src/name_lookup.c, src/notify.h, src/prompt.c, src/toxic.c, src/video_device.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/317)
=> cleanup: Add and fix Wunreachable-code-return, Wunused-macros, and Wformat-nonliteral

.cirrus.yml
It's unreliable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/325)
=> chore: Don't use cirrus cache for bazel.

src/friendlist.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/322)
=> fix: friend tab names default colour now matches custom themes

src/autocomplete.c, src/chat.c, src/conference.c, src/execute.c, src/groupchats.c, src/prompt.c
This commit also fixes an issue where trying to autocomplete a lone forward-slash will spam the window with every possible command
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/327)
=> cleanup: string arrays now contain const strings

src/autocomplete.c
The previous commit made an empty forward-slash not auto-complete the entire list of possible commands, but it also prevented auto-completion using the first character of a peer's name in a group or conference.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/328)
=> fix: regression with autocomplete behaviour

src/api.c, src/audio_call.c, src/chat.c, src/chat_commands.c, src/conference.c, src/conference.h, src/friendlist.c, src/friendlist.h, src/game_base.c, src/game_base.h, src/global_commands.c, src/groupchats.c, src/groupchats.h, src/input.c, src/log.c, src/log.h, src/prompt.c, src/prompt.h, src/settings.c, src/settings.h, src/toxic.c, src/toxic.h, src/video_call.c, src/windows.c, src/windows.h
Windows are no longer global, and we now use a dynamically re-sizing heap array. This removes the arbitrary window limit and is much faster and more memory efficient.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/329)
=> refactor: full windows implementation overhaul

doc/toxic.conf.5, doc/toxic.conf.5.asc, misc/toxic.conf.example, src/chat.c, src/conference.c, src/groupchats.c, src/line_info.c, src/line_info.h, src/log.c, src/log.h, src/message_queue.c, src/settings.c, src/settings.h
This is only a partial implementation. We only colourize normal messages at present. In order to do other types of messages (actions, connection status, mod events etc.) we'll need to change the log format to give us more hints.
This commit also removes seconds from the default log timestamp for consistency with the UI default, and adds the missing config example field for custom log timestamp formats.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/332)
=> feat: re-colourize chat history on load

src/windows.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/337)
=> fix: make sure realloc() called with a 0 value doesn't abort toxic

.github/workflows/ci.yml, src/main.c, src/toxic.c
They are now in main.c.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/339)
=> cleanup: Remove unused macros from toxic.c

src/misc_tools.c, src/misc_tools.h
These escape sequences mess with toxic's window scrolling and line formatting
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/343)
=> fix: filter \t and \v escape sequences from inbound strings

script/build-minimal-static-toxic.sh, src/groupchat_commands.c
Waiting on https://github.com/TokTok/c-toxcore/pull/2709
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/352)
=> chore: More groupchat API changes

src/groupchat_commands.c, src/groupchats.c
We don't keep track of our own last seen, so now instead of showing a last seen of however long you've been in the group, we show an empty value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/361)
=> fix: doing a /whois on yourself no longer shows an incorrect value

src/audio_call.c, src/conference.c, src/conference.h, src/friendlist.c, src/friendlist.h, src/game_base.c, src/game_base.h, src/global_commands.c, src/groupchats.c, src/groupchats.h, src/log.c, src/log.h, src/main.c, src/toxic.h, src/windows.c, src/windows.h
We now use 16-bit ID's for windows and re-use previously discarded ID's instead of using an incrementer. We also now do proper error handling on window creation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/344)
=> refactor: Window ID's and window creation error handling

src/windows.c, test/toxic.test.ts
The message history now stays scrolled to the bottom after making the toxic window smaller, unless you aren't already scrolled to the bottom
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/363)
=> fix: message history position on resize

src/chat.c, src/conference.c, src/conference_commands.c, src/groupchat_commands.c, src/groupchats.c, src/line_info.c, src/line_info.h, src/log.c, src/log.h, src/main.c, src/message_queue.c, src/prompt.c
This isn't perfect but it's close enough for now.
Logs needing the `:` character for extracting nicks from logs is dealt with in https://github.com/TokTok/toxic/pull/348
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/342)
=> feat: re-colourize the rest of logs on load

src/audio_call.c, src/audio_call.h, src/autocomplete.c, src/avatars.c, src/chat_commands.c, src/configdir.c, src/execute.c, src/friendlist.c, src/global_commands.c, src/line_info.c, src/main.c, src/misc_tools.c, src/misc_tools.h, src/toxic_constants.h
These fatal errors aren't catastrophic and can be recovered from.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/356)
=> refactor: Make some fatal memory errors non-fatal

src/video_call.c
With commit 3158aced it's possible for the index to be out-of-bounds if a malloc fails while initializing AV
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/365)
=> fix: make sure call control index is in-bounds for video calls

Makefile, src/init_queue.c, src/init_queue.h, src/main.c, src/toxic.c, src/toxic.h
This functionality was awkwardly placed between main.c and toxic.c. Now it resides on its own as a stand-alone unit.
Also improved documentation and naming scheme, and added some extra null checks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/366)
=> refactor: Move message init queue to separate file

script/build-minimal-static-toxic.sh
- Updated libcurl version
- Also disabled a lot of unnecessary features
```diff
--- curl-configure-before
+++ curl-configure-after
@@ -16,15 +16,15 @@
zstd:             no      (--with-zstd)
GSS-API:          no      (--with-gssapi)
GSASL:            no      (libgsasl not found)
-  TLS-SRP:          enabled
+  TLS-SRP:          no      (--enable-tls-srp)
resolver:         POSIX threaded
IPv6:             enabled
-  Unix sockets:     enabled
+  Unix sockets:     no      (--enable-unix-sockets)
IDN:              no      (--with-{libidn2,winidn})
Build docs:       no
Build libcurl:    Shared=no, Static=yes
-  Built-in manual:  enabled
-  --libcurl option: enabled (--disable-libcurl-option)
+  Built-in manual:  no      (--enable-manual)
+  --libcurl option: no
Verbose errors:   enabled …
```
=> chore: Update the static build script

src/conference.c, src/groupchats.c
The number of peers can change between and within iterations leading to an out of bounds index. Now we just lock the entire loop, which is less efficient but necessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/376)
=> fix: race condition when drawing group/conference peer list

misc/toxic.conf.example, src/line_info.c, src/settings.c, src/settings.h
Introduces new `line_padding` config option, which has a default value of `true` to correspond with the existing line padding behavior added in 8e84ac5.
When set to `false` a message exceeding the width of the window will be wrapped into new lines without an `x_start` number of blanks being printed first. Setting `x_limit` to `max_x` to prevent column padding is precedented by the existing `newline_idx >= 0` block.
Example of the behavior with `line_padding=true`:
```
00:00 - Toxic User: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Integer neque metus, lacinia quis magna ut, laoreet magna.
00:00 - User2: Nam suscipit faucibus justo, ut malesuada neque aliquet at...
This text is misaligned with a message from any user with
a user name of differing length.
```
Example of the …
=> feat: message line padding configuration

BUILD.bazel
Toxic won't compile on windows for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/390)
=> cleanup: Fix layering checks and mark toxic as no-windows.

src/execute.c, src/global_commands.c, src/groupchat_commands.c, src/groupchats.c, src/groupchats.h, src/help.c
This replaces the deprecated tox_group_reconnect command with tox_group_join which now supports the ability to reconnect to groups with a password.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/391)
=> feat: Add the ability to pass a password to the groupchat /rejoin command

src/chat_commands.c, src/chat_commands.h, src/conference.c, src/conference_commands.c, src/conference_commands.h, src/execute.c, src/friendlist.c, src/friendlist.h, src/groupchat_commands.c, src/groupchat_commands.h, src/groupchats.c, src/help.c
Friends from the friend list can now be invited to groups and conferences with the /invite and /cinvite commands respectively.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/387)
=> feat: Allow friend invites from group and conference windows

src/groupchats.c, src/help.c
- The help menu should no longer flicker in group chats
- The main menu now properly shows the exit option
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/392)
=> fix: help menu bugs

src/groupchats.c, src/groupchats.h, src/main.c, src/toxic.h, src/windows.c, src/windows.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/395)
=> cleanup: Stop using deprecated names for things in tox.h.

doc/toxic.conf.5, doc/toxic.conf.5.asc, misc/toxic.conf.example, src/api.c, src/audio_call.c, src/audio_device.c, src/chat.c, src/conference.c, src/groupchats.c, src/main.c, src/misc_tools.c, src/misc_tools.h, src/notify.c, src/prompt.c, src/python_api.c, src/qr_code.c, src/settings.c, src/settings.h, src/toxic.c, src/toxic.h, src/toxic_constants.h, src/video_call.c, src/windows.c
A list of blocked words can now be added to the config file. Any message that contains a word on the list will not be able to send, and will cause an error message to be displayed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/394)
=> feat: Add word block list to config

.cirrus.yml, src/game_base.c, src/video_call.c, src/video_device.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/399)
=> fix: null pointer dereference on video call activation

.circleci/config.yml, .cirrus.yml
Maybe we can add a freebsd build to cirrus.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/402)
=> chore: Move bazel build to circleci for now.

src/settings.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/401)
=> fix: memory leak when reloading config settings

src/settings.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/404)
=> fix: pointer use after free on config reload failure

src/settings.c, src/term_mplex.c, src/toxic.h
This fixes https://github.com/JFreegman/toxic/issues/674
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/toxic/406)
=> fix: config changes to mplex auto-away now work in running sessions
